#include <curses.h>

struct obj_RAPA_FloStr1{
    int x, y; // current location and survival life
    static const int shape_size_y = 1, shape_size_x = 17;
    void appear4(const int &move_y, const int &move_x){
        mvaddstr(move_y-this->shape_size_y+1, move_x, "1. RTC control system (7.13-8.28) ");
        // mvaddstr(move_y-this->shape_size_y+2, move_x,"| Python |");
        // mvaddstr(move_y-this->shape_size_y+3, move_x," -------- ");
    }
};

/*  
"1. RTC control sy"
"stem (7.13-8.28) "
"- Data structure "
"and algorithm, Li"
"nux Fundamental &"
" Shell Programmin"
"g, HTML5/CSS, Jav"
"aScript (Ajax, Xm"
"l, node.js), Pyth"
"on syntax, Web Fr"
"amework (Django) "
"DBMS structure an"
"d data modeling, "
"Database (SQL/NoS"
"QL) 2. Big data r"
"eal-time analysis"
" (8.31-9.4) - Int"
"roduction to Stat"
"istics, Data Craw"
"l & Scraping 1. R"
"TC control system"
"-Sub Project (9.7"
"-9.11) Data analy"
"sis using Python "
"library 2. Big da"
"ta real-time anal"
"ysis (9.14-10.23)"
" - Visualization,"
" Data preprocessi"
"ng, Distributed s"
"ystem (Hadoop, Sp"
"ark, etc.), Big D"
"ata Real-Time Ana"
"lysis-Sub Project"
" 2-1. Data Analys"
"is Mentoring Data"
" Analysis Mentori"
"ng 9.26/10.17 Sat"
"/Sat 3. Comprehen"
"sive flight [on-s"
"ite training] (10"
".27-11.9) Underst"
"anding the types "
"and structure of "
"drone equipment, "
"Aviation related "
"laws and ultra-li"
"ght aircraft avia"
"tion laws, Take-o"
"ff and landing an"
"d emergency proce"
"dures, Aerial ope"
"ration and non-su"
"perficial operati"
"on, Comprehensive"
" Flight-Sub Proje"
"ct 4. Custom dron"
"e production and "
"control system (1"
"1.10-12.3) - Embe"
"dded system, Netw"
"ork for data tran"
"smission, Flight "
"mechanics, Custom"
" drone production"
" and control syst"
"em-Sub Project 5."
" Autonomous fligh"
"t using artificia"
"l intelligence (1"
"2.4-1.26) - Intro"
"duction to Artifi"
"cial Intelligence"
", machine learnin"
"g, Deep learning "
"algorithms, Image"
" processing using"
" OpenCV, OpenCV i"
"mage data set det"
"ection learning, "
"Self-driving car "
"learning, Drone a"
"utonomous flight "
"using central con"
"trol system-Main "
"Project 5-1. Arti"
"ficial Intelligen"
"ce Mentoring Arti"
"ficial Intelligen"
"ce Mentoring 12.1"
"9/1.9 Sat/Sat 6. "
"Design Thinking P"
"roject planning t"
"hrough brainstorm"
"ing using design "
"thinking 10.5-10."
"6 7. Idea Bank vo"
"cational career t"
"raining, resume +"
" personal letter "
"correction, consu"
"lting on how to a"
"pply for employme"
"nt through compan"
"y and related job"
" analysis 10.26/1"
"1.21/11.28 Mon/Sa"
"t/Sat 8. Final Pr"
"oject (1.11-1.27)"
*/